# The portal [icos, cities]
portal: "cities"

# The reason
# [cities, cte-hr, cte-gcp,
#  edgar-ch4, edgar-co2,
#  fluxcom-et, fluxcom-et-t, fluxcom-gpp, fluxcom-nee,
#  gcp-inversions
#  lpj-guess-eu, lpj-guess-global,
#  paris,
#  stilt-docs,
#  vprm]
reason: "cities"

# Where is your data?
data_dir: "/home/user/data"
pattern: "*"

# The critical part ###################
archive_files: false
try_ingest: false
calculate_hash_sum: false
archive_json: false

upload_to_production: false
upload_meta_data: false
upload_data: false
#######################################

# Where do you want your metadata?
master_dir: "archives/cities"
archive_path: "archives/cities/archive.json"
json_standalone_files: "archives/cities/json-standalone-files/"
json_collection_standalone_files: "archives/cities/json-collection-standalone-files/"

# Show and tell
previous_collection: null
try_ingest_subprocesses: 1
show_input_files: true
show_separator: true
show_progress_archive_files: true
show_progress_try_ingest: true
show_progress_archive_json: true
show_progress_upload_meta_data: true
show_progress_upload_data: true
overwrite_archive: true

